spring:
  application:
    name: MealMate
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/MealMate_DB
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8765

